# Generated by Django 3.2.9 on 2022-03-12 18:36

import ObjectDetectionAnalyzer.upload.ModelTypes
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('ground_truth_path', models.FilePathField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'userId')},
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('datasetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.dataset')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'datasetId', 'userId')},
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label_map_path', models.FilePathField()),
                ('path', models.FilePathField()),
                ('type', models.CharField(choices=[(ObjectDetectionAnalyzer.upload.ModelTypes.ModelTypes['PYTORCH'], 'PyTorch'), (ObjectDetectionAnalyzer.upload.ModelTypes.ModelTypes['TENSORFLOW1'], 'TensorFlow 1'), (ObjectDetectionAnalyzer.upload.ModelTypes.ModelTypes['TENSORFLOW2'], 'TensorFlow 2'), (ObjectDetectionAnalyzer.upload.ModelTypes.ModelTypes['YOLOV3'], 'Yolo v3'), (ObjectDetectionAnalyzer.upload.ModelTypes.ModelTypes['YOLOV5'], 'Yolo v5')], max_length=7)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'type', 'userId')},
            },
        ),
    ]
