FROM node:14.17.0-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY Frontend/package.json /app
RUN npm install
COPY Frontend/ /app/
RUN npm run build --prod

FROM nginx:1.20.1
COPY --from=build-step /app/dist/Frontend /usr/share/nginx/html
EXPOSE 4200:80
